export const tracksData = [
  {
    id: 1,
    title: "Guilt",
    artist: "Nero",
    album: "Welcome Reality",
    duration: "4:44",
    audioUrl: "/audio/guilt.mp3",
    cover: "/img/playlist01.png",
  },
  {
    id: 2,
    title: "Elektro",
    artist: "Dynoro, Outwork, Mr. Gee",
    album: "Elektro",
    duration: "2:22",
    audioUrl: "/audio/elektro.mp3",
    cover: "/img/playlist01.png",
  },
  {
    id: 3,
    title: "I'm Fire",
    artist: "Ali Bakgor",
    album: "I'm Fire",
    duration: "2:22",
    audioUrl: "/audio/im-fire.mp3",
    cover: "/img/playlist01.png",
  },
  {
    id: 4,
    title: "Non Stop",
    remix: "(Remix)",
    artist: "Стоункат, Psychopath",
    album: "Non Stop",
    duration: "4:12",
    audioUrl: "/audio/non-stop.mp3",
    cover: "/img/playlist02.png",
  },
  {
    id: 5,
    title: "Run Run",
    remix: "(feat. AR/CO)",
    artist: "Jaded, Will Clarke, AR/CO",
    album: "Run Run",
    duration: "2:54",
    audioUrl: "/audio/run-run.mp3",
    cover: "/img/playlist02.png",
  },
  {
    id: 6,
    title: "Eyes on Fire",
    remix: "(Zeds Dead Remix)",
    artist: "Blue Foundation, Zeds Dead",
    album: "Eyes on Fire",
    duration: "5:20",
    audioUrl: "/audio/eyes-on-fire.mp3",
    cover: "/img/playlist02.png",
  },
  {
    id: 7,
    title: "Mucho Bien",
    remix: "(Hi Profile Remix)",
    artist: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
    album: "Mucho Bien",
    duration: "3:41",
    audioUrl: "/audio/mucho-bien.mp3",
    cover: "/img/playlist03.png",
  },
  {
    id: 8,
    title: "Knives n Cherries",
    artist: "minthaze",
    album: "Captivating",
    duration: "1:48",
    audioUrl: "/audio/knives-n-cherries.mp3",
    cover: "/img/playlist03.png",
  },
  {
    id: 9,
    title: "How Deep Is Your Love",
    artist: "Calvin Harris, Disciples",
    album: "How Deep Is Your Love",
    duration: "3:32",
    audioUrl: "/audio/how-deep-is-your-love.mp3",
    cover: "/img/playlist03.png",
  },
  {
    id: 10,
    title: "Morena",
    artist: "Tom Boxer",
    album: "Soundz Made in Romania",
    duration: "3:36",
    audioUrl: "/audio/morena.mp3",
    cover: "/img/playlist01.png",
  },
];
